## YAML Template.
---
app:
  brand: 'Backtest de portefeuille'
  title: 'backtester UC'
  search: false
  menu:
    Assurance Vie: /portfolio
    Jeu : /timeTheMarket
    Doc:
      To do...: /help

 